### ISSUE TITLE
SE Carcajou Canyon, NWT

### ISSUE THREAD

**Issue by cvavrus** [UW-Macrostrat/burwell-processing#341]
**Name:**
Fallas, K.M. and MacNaughton, R.B., 2014. Geology, Carcajou Canyon (southeast), Northwest Territories; Geological Survey of Canada, Canadian Geoscience Map 96, scale 1:100 000. doi:10.4095/292288

**Source URL:**
https://doi.org/10.4095/292288

**Estimated scale:**
large

**Folder name:**
nwt_carcajou_se

**Dataset names:**
nwt_carcajou_se
nwt_carcajou_se_lines
nwt_carcajou_se_points

**Number of bedrock polygons:**
232

**Lithology field:**
lith_list

**Time field:**
use_age

**Stratigraphy name field:**
strat_name

**Description field:**
descrip

**Comments field:**

**Comments:**

## Todo:

- [x] Insert new source record
- [x] Add data to database
- [x] Process and add to homogenized tables
- [x] Process and import lines
- [x] Process and import points
- [x] Match
- [x] Roll tiles

**Comment by cvavrus** [comment]
Suggested inserts:
```
INSERT INTO maps.large (orig_id,source_id,name,age,lith,descrip,comments,strat_name,t_interval,b_interval,geom) 
SELECT gid,1,map_unit,use_age,lith_list,descrip,genesis,strat_name,late_id,early_id,ST_MakeValid(geom) FROM sources.nwt_carcajou_se where geom is not null;
```

```
INSERT INTO lines.large (orig_id,source_id,name,descrip,new_type,geom) 
SELECT gid,1,name,concat_ws('; ',subfeature,concat('orientation ',attitude),concat('location ',confidence),concat('age ',concat(max_age,'- ',min_age))),new_type,ST_MakeValid(geom) FROM sources.nwt_carcajou_se_lines where new_type is not null and geom is not null;
```
points unclear

**Comment by cvavrus** [comment]
Drift map units in a separate .shp file

**Comment by cambro** [comment]
source_id 217

**Comment by cambro** [comment]
same error as 216

**Comment by cambro** [comment]
```
$ macrostrat process map_source 217
rm: cannot remove 'large217.*': No such file or directory
rm: cannot remove 'large217_rgeom.*': No such file or directory
[i] Mismatched .dbf and .shp record count -- possible data loss.
[dissolve] Dissolved 0 features into 0 features
[o] Wrote large217_rgeom.shp
[o] Wrote large217_rgeom.shx
[o] Wrote large217_rgeom.dbf
[o] Wrote large217_rgeom.prj
Shapefile type: Polygon
Postgis type: MULTIPOLYGON[2]
     Validating geometry...
Traceback (most recent call last):
  File "/usr/local/bin/macrostrat", line 11, in <module>
    load_entry_point('macrostrat-cli', 'console_scripts', 'macrostrat')()
  File "/data/projects/macrostrat-cli/cli/cli.py", line 90, in main
    script.run()
  File "/data/projects/macrostrat-cli/cli/commands/process.py", line 61, in run
    script.run(self.args[2:])
  File "/data/projects/macrostrat-cli/cli/commands/process_scripts/map_source.py", line 65, in run
    rgeom.run((source_id, ))
  File "/data/projects/macrostrat-cli/cli/commands/process_scripts/rgeom.py", line 99, in run
    if '--simple' in self.args[0]:
IndexError: tuple index out of range
```

**Comment by cambro** [comment]
https://dev.macrostrat.org/burwell/#10/64.2506/-126.4980

**Comment by cvavrus** [comment]
Suggested insert:
```
INSERT INTO points.points (orig_id,source_id,strike,dip,dip_dir,point_type,comments,geom) 
SELECT gid,1,strike,dip,dip_dir,point_type,concat_ws('; ',subfeature,remarks),ST_MakeValid(geom) FROM sources.nwt_carcajou_se_points where point_type is not null and geom is not null;
```
